version: "3.8"
services:
  db:
    image: postgres:14.0-alpine
    networks:
      - backend
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - "/opt/postgresql/data/:/var/lib/postgresql/data/"
  dj:
    build: .
    command: ./wait-for-it.sh db:5432 -- sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "80:8000"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend: